{% set name = "python-editor" %}
{% set version = "1.0.3" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "a3c066acee22a1c94f63938341d4fb374e3fdd69366ed6603d7b24bed1efc565" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - editor

about:
  home: https://github.com/fmoo/python-editor
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Programmatically open an editor, capture the result.'
  dev_url: https://github.com/fmoo/python-editor

extra:
  recipe-maintainers:
    - pmlandwehr
