# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "m/nmSXJ4Yj9Zcflti74R4ApCttv37Anjo5VVS819KJaUp5o8w33VjlLfFaDC/1sCDdI9a1LZo1sA6GyWIuyD6hJ5ETaiUMY2r92UR72A0V27/26A/QBQWsL7vzsLk5JCnHOo8/EPv5HC8jQpj5ppwFHxGnZz51jw6nc+SS91mYqpvLhGp8+FUusHhfKBsoK5L3xUOIdHiww4IzqSI+AbJxu6Y2yS4IqipdF/QijC4UEfL8MSOvuo34SPhiC56LN1ZvobWJVpeyShEz6f7YkSGG2thSKUqMiqh/ukvqaICqyQBy54wT6+xxqHVi8UhPkxYTaxoFbRlH5zLT04Rz77q44Pe1AH1QI9xhCdunvUcZLYfPsQMuInWvsEDwWqOF0UA1z/BNotgqp0Ysm6afqwddKhjh1cDxm4sf2JCIw+wxRiDdIJNPBxCMjA/mrxwUoElF1V9fo+2lICp6apyddHZl+xZmtdrkLuAfiKpivMHJYLM7/VUBb6JwrzobuAOqfVPRad8Kps6UF1H7rOfgfNkRW7axtigAoTOGGl/PIhR8H3vm4E/dHeTv9IYpQp72tOgby/YyXeU/ZSo1U5MPTdFYnIn2aODRl+U4Kz0EfkM2/OdpS9LY0vB8pVC2dg8MIbJfobqmyFkSTghSvcPbISOAGuGLSg1kvk2RE4nYHp+4U="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
