travis:
  secure:
    BINSTAR_TOKEN: gN8NAYo3uvbJUM0w/A642Tfvn/XhKhY+LtEKrYi67Y5Nh8j+7XTLOWGcqNrQg6D7jR8wCWnXb37os/g3w7rwo9mREeX4BjekvA7i7vvKQnehmdVuvXLx/rwmwkaOwrvOf/237CRmg8Z+rmMGmaJVqzeBX3wPgsE25CIgpExo5Y2uuuAKJScgqtEkGSJUGKm8VKAAq333EE4k5Shawr25Jsmc0r9scQcWisyXTmUXnafjAdGu9O4zsb4vBoQRbby6Ys/Ia7gGKT/WxONK3oNyNFS0CAvqkTerHLtaNASuPd67SjEg7FoowHj+l4Pj6AzXK1fZ+LsN8VeFRIwR6tQK1qN0pdnTPkrkX8AcnCoYRRg1wbHAWvERHK4wHtaaZWkRdAOHRHL+BeVj/A4uJyWr5HPmRLi5QUfA8AJW8zXMSPYbORXJKjE+kQ+8KYImX9g0YjzPoecr5qslV+lqdm/xLQAS16UtfUOf21CnPdnNcgi7cFNB8uLLmmH+LKMHtN6XEvhX2UQ0mNfGVDEXl4Iq3BxjLtsLF2fY9kcWFBrtZGyF+iKdt7XeWb77jH4V+X7uPSEeRgVlHAM6nd8QCXxZNCcozZVOKUX/HdVN9Piso9fHE+xtTjb98SCSOr8BN4z+Jj6HLya+amBKECPmM+0Z/8fp93z35ieXSJrlsVLmR8w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
