travis:
  secure:
    BINSTAR_TOKEN: QEoa9UQq5wOFpLCM7bKvgem3nNQRNxKc/dy5JbbOl8AcuXXoEUe9Am0ElhbQIRTS7uOmVOTDgvNTvezsR/aq96ZrzNLrbyeTtQa9s2Xx/9/rk3ht/3enKs1yMXJH7NqDMnOjfd64bIPNx8R31Aoki8clnbSmx/1lg2NWBG7IdxJ/EpNTOKxVJd7t+wnHpKBfAhFuVpR//VgjztFrQ2/00xfJLih/EnrKhu61D7e5+JFAXHLXA4+30X4CPyRJsjVP/tDwcylsPfOj1JNGpL82gvjWQIHOSsv6nE1R+eMIQWaEk2sPtVTfJctzUq5VlLil13zM7ZI5dDkw/GRkBkRL8pqHyFudxEk7Rio7cz8G9YVEHvasgkgL0qCfrj3rjBXfSTZmD+ZZfHIr3u6r/ypMpm0zAx7h1u2IlhYxN1aAdEMYCyRJKCeah3prRWXObAsq0pIXGCetdI/dfnzuhjs+6J418LoP9MjRMUGE68W5PPplBtvrT7g97J7i02H2inJCeSvmxHc3ZgpJHLS/C0nbMSwtXvQoCpZhYR2CH3ScYRpXl+oTFR6+CzvgXbE+9fuNVhQZouSTO3O1TA/UcQOOhp8kOPjBMf4NlVFoYsmCOP3BPIYP3hu6UtTwbt3+g6KKyMlz0npV7kWH93azJ3pNSJK6Urw8J2fBmXwAHH3GNFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
