travis:
  secure:
    BINSTAR_TOKEN: qcUGF9ZnbEfvAFp3sru6J+ymMSJJSV1rqkNG6o5tcBGMBYvzijMbUcDGWhhfERTI7ofU8vrT25bKI3mQmTreMvTZkFFp9u3zkqcNl4Td4k3V7qUQE3wqqAe/ZDYFzn2z0oQ5UJUUy0tDFZoiHSbjhnd7Id2WFf5QogTke0Cjnhhb4//d5MePA3n7/0kBl2n+6+DCcbuM8+pjMTVxTXeWKMxodYmTaLlQ2Gskx0bwmwQg4lRqPwV6wc0Duc0rYFvWMqqbArSq6i23FQxfa+IHDE23kky/luDnpHjFkcdpZZabrJepeqlwrbfhZgG075qrMjkqu4+calOohk1NCn7y3BjU3I50uNDeJrQM8rERra5QTOLtI51xMp87ssi5Y0cnUiCfhu3h3yl4RNFz/iXG6K+5/n7woDnvw7vTO50h59X/QOD7hQIsshEXlBEtqb4YY4Hxf3ursk+vkoEmI88O3kLyd7zkJ78qKYoRLqPIUdpZsmkEVF2nOvGriTv5PCDkYNbwcqWPbAkksSie0NgKq8LUOOAUdaG9Rcxy0YQOAmqTTF5PaAyDzWRYxQ9DKWpCCQLf4zZM8gVmDWRTmQAU0ah8HoQWSV35dS28QLQorZtPE3h2SpNXGNUfuHC3vaz0gWGOBX1KzQcMzri48CnTGwXfvrTRQ3/R+n6CAkkJxZ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
