travis:
  secure:
    BINSTAR_TOKEN: m/nmSXJ4Yj9Zcflti74R4ApCttv37Anjo5VVS819KJaUp5o8w33VjlLfFaDC/1sCDdI9a1LZo1sA6GyWIuyD6hJ5ETaiUMY2r92UR72A0V27/26A/QBQWsL7vzsLk5JCnHOo8/EPv5HC8jQpj5ppwFHxGnZz51jw6nc+SS91mYqpvLhGp8+FUusHhfKBsoK5L3xUOIdHiww4IzqSI+AbJxu6Y2yS4IqipdF/QijC4UEfL8MSOvuo34SPhiC56LN1ZvobWJVpeyShEz6f7YkSGG2thSKUqMiqh/ukvqaICqyQBy54wT6+xxqHVi8UhPkxYTaxoFbRlH5zLT04Rz77q44Pe1AH1QI9xhCdunvUcZLYfPsQMuInWvsEDwWqOF0UA1z/BNotgqp0Ysm6afqwddKhjh1cDxm4sf2JCIw+wxRiDdIJNPBxCMjA/mrxwUoElF1V9fo+2lICp6apyddHZl+xZmtdrkLuAfiKpivMHJYLM7/VUBb6JwrzobuAOqfVPRad8Kps6UF1H7rOfgfNkRW7axtigAoTOGGl/PIhR8H3vm4E/dHeTv9IYpQp72tOgby/YyXeU/ZSo1U5MPTdFYnIn2aODRl+U4Kz0EfkM2/OdpS9LY0vB8pVC2dg8MIbJfobqmyFkSTghSvcPbISOAGuGLSg1kvk2RE4nYHp+4U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
